# See:
#   FLIT https://flit.pypa.io/
#   TOML format: https://toml.io/en/
#
# Updating PyPi:
#   source venv/bin/activate
#   flit build
#   flit publish

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hikecalc"
authors = [{name = "S. Pothier"}]
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]

[project.urls]
"Homepage" = "https://pypi.org/project/hikecalc/"
"Bug Tracker" = "https://github.com/pypa/hikecalc/issues"
"Documentation" ="https://hikecalc.readthedocs.io/en/latest/"

[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/index.html
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
