# global change "hc" => "*hikecalc*"

* COMMENT PRESCRIPT
Uses src blocks.
Customize org-bable-load-languages to include: dot, sh

* Overview

The *hikecalc* is intended to help you find and plan hikes suitable for your
available time and energy. It lets you pick alternatives that include
various waypoints and provides total and cummulative miles.  You
provide constraints, it does the figuring.

The data file for *hikecalc* is a simple formatted text file. You can
write your own or use data files that come with the
package. Generally, one data file reflects distances between points in
a fairly local region.  For instance, one of the supplied data files
is for the Catalina Mountain range that is North of Tucson, Arizona.


* Example Usage
#+BEGIN_SRC sh :session pyenv :dir ~/sandbox/hikecalc :exports none :results output
source  hc_env/bin/activate
#+END_SRC
#+RESULTS:

** Get help
#+BEGIN_SRC sh :session pyenv :results output :exports both
echo "Project home2=$PROJ"
hc --help
#+END_SRC
#+RESULTS:

#+BEGIN_SRC sh :session pyenv :results output :exports both
hc shortest --help
#+END_SRC


** What trailheads are in the file?

#+BEGIN_SRC sh :session pyenv  :results output :exports both
hc th data/catalina.dat
#+END_SRC
#+RESULTS:

** What waypoints are in the file?
: hc wp data/catalina.dat


** How far is it from Sabino visitor center to The Window?
: hc shortest -w SabinoTH -w TheWindow  data/catalina.data
: The shortest distance from "SabinoTH" to "TheWindow" is 8.8 miles via:
:   SabinoRoad1, RattlesnakeJct, CardiacGap, GeronimoMeadow, BridalVeilFalls, CathedralJct, TheWindow

** What is the detail distance from Butterfly to Palisades Ranger Station?
: hc shortest -w ButterflyTH  -w PalisadesRangerTH --details data/catalina.dat 
: The shortest distance from "ButterflyTH" to "PalisadesRangerTH" is 5.7 miles via:
:     1.4   1.4  CrystalSprTop
:     1.8   3.2  NovioSpring
:     2.0   5.2  PalRangJct
:     0.5   5.7  PalisadesRangerTH

* TODO (NOT IMPLEMENTED YET)

** Types
- OB :: out-and-back, from Trail-Head to some destination. Retrace
        path back to TH.
- Loop :: Start and end at the same TH. But don't retrace path.
- Through :: Start and end at different Trail-Heads.  You probably
             need a shuttle to get back to where you started.

** Things you can do
For each path, you can get a simple summary of the total, or you can
get a segment by segment running total of the milage.

- [ ] OB (Out and Back) - "Round Trip".  
  + You provide TH and turn around point
  + Returns the shortest route out and back to your turn-around point
    (turn-around point must be a waypoint in the data file)
- [ ] OB - max distance
  + You provide TH and the maximum distance you want to hike.
  + Reports possible turn around points with round-trip distance to
    each.
- [ ] Through hike with shuttle
  + You provide start and end TH.
  + Report 
