# global change "hc" => "*hikecalc*"

* COMMENT PRESCRIPT
NOTE: This file includes some org mode src blocks. Some are for using
graphviz to generate figure, some to use SH to run programs described
here to get their usage documentation. To get good export, emacs must
be configured appropriately.

Customize org-bable-load-languages to include: dot, sh

* Overview

The *hikecalc* is intended to help you find and plan hikes suitable for your
available time and energy. It lets you pick alternatives that include
various waypoints and provides total and cummulative miles.  You
provide constraints, it does the figuring.

The data file for *hikecalc* is a simple formatted text file. You can
write your own or use data files that come with the
package. Generally, one data file reflects distances between points in
a fairly local region.  For instance, one of the supplied data files
is for the Catalina Mountain range that is North of Tucson, Arizona.


* Example Usage

#+BEGIN_SRC sh :session hcenv :dir ~/sandbox/hikecalc :exports none :results output
source  hc_env/bin/activate
export CATDATA=~/sandbox/hikecalc/data/catalina.dat
PROJ=`pwd`
#+END_SRC
# RESULTS:

** Get help
#+BEGIN_SRC sh :session hcenv :results output :exports both
hc --help
#+END_SRC

#+BEGIN_SRC sh :session hcenv :results output :exports both
hc shortest --help
#+END_SRC


** What trailheads are in the file?

#+BEGIN_SRC sh :session hcenv  :results output :exports both
hc th $CATDATA
#+END_SRC


** What waypoints are in the file?
#+BEGIN_SRC sh :session hcenv  :results output :exports both
hc wp $CATDATA
#+END_SRC



** How far is it from Sabino visitor center to The Window?
#+BEGIN_SRC sh :session hcenv  :results output :exports both
hc shortest -w SabinoTH -w TheWindow  $CATDATA
#+END_SRC

** What is the detail distance from Butterfly to Palisades Ranger Station?
#+BEGIN_SRC sh :session hcenv  :results output :exports both
hc shortest -w ButterflyTH  -w PalisadesRangerTH --details $CATDATA 
#+END_SRC

* Example: Use HC + org-mode to generate planning document with hike options
** Grand Canyon, East of Hermit
:PROPERTIES:
:EXPORT_FILE_NAME: grand-canyon-hermitoctober
:END:

#+BEGIN_SRC sh :session hcenv :exports none :results output
source ~/sandbox/hikecalc/hc_env/bin/activate
export DATA=~/sandbox/hikecalc/data/grand-canyon.dat
#+END_SRC
#+RESULTS:

** COMMENT Baseline
#+BEGIN_SRC sh :session hcenv :exports both :results output
hc shortest --details -w South_Kaibab_TH -w Hermit_TH $DATA
#+END_SRC
#+RESULTS:

# Use HC with ~/sandbox/hikecalc/data/grand-canyon.dat
** "The Works" (4 nights)
*Covers everything Steve has burning need to do between Kaibab and Hermit.*
Hits the Colorado - TWICE!

Includes optional side-hikes to:
1. Plateau_Point   at Sunset! (day pack)
2. Granite_Rapids  (camp)
3. Hermit_Rapids   (with time to relax, day pack)

No Plateau sunset. Could do Plateau at end of Day 1 but it would add
to overall miles and make day one 3 miles longer.

#+BEGIN_SRC sh :session hcenv :exports results :results output
hc shortest --details -w South_Kaibab_TH -w  Plateau_Point -w Granite_Rapids -w Hermit_Rapids  -w Hermit_TH  \
  -c Indian_Garden_CG Camp1 -c Horn_Creek Camp2 -c Granite_Rapids Camp3 -c Hermit_Creek Camp4 $DATA
#+END_SRC
#+RESULTS:


*** COMMENT OBSOLETE
> hc shortest --details -w South_Kaibab_TH -w Indian_Garden_CG -w  Plateau_Point -w Horn_Creek -w Granite_Rapids -w Hermit_Rapids -w Hermit_Creek  -w Hermit_TH  -c Indian_Garden_CG -c Horn_Creek -c Granite_Rapids -c Hermit_Creek $DATA

: The shortest distance from "South_Kaibab_TH" to "Hermit_TH" is 39.0 miles via:
:     0.0   0.0  South_Kaibab_TH	Start
:     1.5   1.5  Cedar_Ridge	
:     1.5   3.0  Skeleton_Point	
:     1.4   4.4  Tipoff	
:     4.4   8.8  Indian_Garden_CG	Camp 1
:     0.7   0.7  Plateau_Point_JCT	
:     0.8   1.5  Plateau_Point	
:     0.8   2.3  Plateau_Point_JCT	
:     1.8   4.1  Horn_Creek	Camp 2
:     4.8   4.8  Salt_Creek	
:     2.1   6.9  Cedar_Spring	
:     1.3   8.2  Monument_Creek	
:     1.6   9.8  Granite_Rapids	Camp 3
:     1.6   1.6  Monument_Creek	
:     3.5   5.1  Hermit_Creek	Camp 4
:     1.5   1.5  Hermit_Rapids	
:     1.5   3.0  Hermit_Creek	Camp 4
:     1.2   1.2  Tonto_JCT	
:     7.0   8.2  Hermit_TH	DONE

** "A Quicky" (2 nights)
*The shortest trip that finishes Steve's Thanksgiving hike* EXCEPT it adds
Plateau_Point at sunset (day pack).
- No South Kaibab.
- No River.

#+BEGIN_SRC sh :session hcenv :exports results :results output
hc shortest --details -w Bright_Angel_TH -w Plateau_Point -w Indian_Garden_CG -w Hermit_TH -c Indian_Garden_CG Camp1 -c Monument_Creek Camp2 $DATA
#+END_SRC
#+RESULTS:

** "Git'r Done!" (2 nights)
*Minimize camping, but hike a long day 2 (which is all Tonto).*
- No River
- No Plateau sunset.

Could do Plateau at end of Day 1 but it would add
to overall miles and make day one 3 miles longer.

#+BEGIN_SRC sh :session hcenv :exports results :results output
hc shortest --details -w South_Kaibab_TH -w Indian_Garden_CG -w  Plateau_Point -w Hermit_TH  -c Indian_Garden_CG Camp1 -c Monument_Creek Camp2 $DATA
#+END_SRC
#+RESULTS:

** "The Middle Way"  (3 nights)
*A compromise of the other options.*
- Plateau_Point at sunset (day pack).
- Hits the river once (day pack).

#+BEGIN_SRC sh :session hcenv :exports results :results output
hc shortest --details -w South_Kaibab_TH -w  Plateau_Point -w Indian_Garden_CG  -w Hermit_Rapids -w Hermit_Creek  -w Hermit_TH  \
 -c Indian_Garden_CG Camp1 -c Horn_Creek Camp2 -c Hermit_Creek Camp3 $DATA
#+END_SRC
#+RESULTS:


* TODO (NOT IMPLEMENTED YET)

** Types
- OB :: out-and-back, from Trail-Head to some destination. Retrace
        path back to TH.
- Loop :: Start and end at the same TH. But don't retrace path.
- Through :: Start and end at different Trail-Heads.  You probably
             need a shuttle to get back to where you started.

** Things you can do
For each path, you can get a simple summary of the total, or you can
get a segment by segment running total of the milage.

- [ ] OB (Out and Back) - "Round Trip".  
  + You provide TH and turn around point
  + Returns the shortest route out and back to your turn-around point
    (turn-around point must be a waypoint in the data file)
- [ ] OB - max distance
  + You provide TH and the maximum distance you want to hike.
  + Reports possible turn around points with round-trip distance to
    each.
- [ ] Through hike with shuttle
  + You provide start and end TH.
  + Report 
